spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      url: jdbc:mysql://${efps.datasource.host}:${efps.datasource.port}/${efps.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: ${efps.datasource.username}
      password: ${efps.datasource.password}
      driver-class-name: ${efps.datasource.driver-class-name}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath:/mapper/*.xml"
