efps:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.24.6
    port: 3306
    database: pc_assist
    username: root
    password: 194044
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key: LTAI4GKZJ7YKZ8XJ
    secret-key: 6Z6ZJ5ZJ6ZJ6ZJ6Z
    bucket: efps-bucket
redis:
    host: 192.168.24.6
    port: 6379
    password: 123456
    database: 0
    timeout: 2000
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-wait: 10000